language: python

python: 3.6

sudo: false

addons:
  apt:
    packages:
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev

env:
 - TOX_ENV=py27
 - TOX_ENV=py34
 - TOX_ENV=py36
 - TOX_ENV=docs
 - TOX_ENV=quality

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email: false
